name: Build and Release CercubePlus

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

  name: Create the DEB

   permissions:
     contents: write

   on:
     push:
       tags:
         - 'v*'

   jobs:
     Create_Packages:
       name: Create Package
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3
           with:
             path: "main"

         - name: Copy script files around to stop .github from being added to the package then build the package
           run: |
             mkdir main
             cp -Rf main/usr main/etc main/DEBIAN main
             dpkg-deb --build main com.arichorn.cercubeplusextra.deb

         - name: Release the Package
           uses: softprops/action-gh-release@v1
           with:
             files: com.arichirn.cercubeplusextra.deb
